name: Deploy Frontend to Windows Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend with secrets as env vars
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
        run: npm run build
        env:
          NEXT_PUBLIC_CLIENT_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CLIENT_SPACE_ID }}
          NEXT_PUBLIC_CLIENT_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CLIENT_ACCESS_TOKEN }}

      - name: Copy build output to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".next,public,package.json,package-lock.json"
          target: "C:/inetpub/vhosts/pijaossalud.com/gesinova.pijaossalud.com"
          strip_components: 0

      - name: Stop NSSM service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            nssm stop gesinova-frontend || echo Already stopped

      - name: Install only production deps on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /d C:\inetpub\vhosts\pijaossalud.com\gesinova.pijaossalud.com
            npm ci --only=production

      - name: Start NSSM service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            nssm start gesinova-frontend || echo Already started
