name: Deploy Frontend to Windows Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Copy frontend build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".next,public,package.json,package-lock.json"
          target: "C:/inetpub/vhosts/pijaossalud.com/gesinova.pijaossalud.com"
          strip_components: 0

      - name: Restart NSSM frontend service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd C:\inetpub\vhosts\pijaossalud.com\gesinova.pijaossalud.com
            npm install --omit=dev --no-audit --no-fund
            npm run build
            nssm stop Gesinova-Frontend
            nssm start Gesinova-Frontend
